# Generated by Django 3.0.6 on 2020-05-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200518_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='name',
        ),
    ]
