# Generated by Django 3.0.6 on 2020-05-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200518_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationoutcome',
            name='simulation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='core.Simulation'),
        ),
    ]
